name: Down-Stream Version AutoMerger
description: Version based auto merging 
author: Michael Lodge-Paolini

branding:
  icon: git-merge
  color: green

inputs:
  production-branch:
    description: Primary branch matching the production environment.
    required: true
    default: main
  development-branch:
    description: Optional Branch where active development is integrated into.
    required: false
    default: develop
  release-pattern:
    description: Release Branch naming pattern
    required: false
    default: 'release/'
  merge-message-template:
    description: Template to generate the commit message, see README.md for more info
    required: false
    default: Auto Merged {source_branch} into {target_branch}
  pr-on-failed-merge:
    description: (yes/no) If a merge fails, create a pull request instead.
    required: false
    default: yes
  pr-title-template:
    description: Template to generate a PR title from, see README.md for more info
    required: false
    default: Failed Auto Merged {source_branch} into {target_branch}

outputs:
  details:
    description: details of what this action performed

runs:
  using: 'node12'
  main: 'dist/index.js'
